import type {Env} from "../env";import {id,now} from "../core/types";
export class Db{constructor(private readonly env:Env){}
async ensureOrganization(orgId:string,name="Default Organization"){await this.env.DB.prepare("INSERT OR IGNORE INTO organizations(id,name) VALUES(?,?)").bind(orgId,name).run();return orgId;}
async createOrganization(name:string){const orgId=id("org");await this.env.DB.prepare("INSERT INTO organizations(id,name,created_at,updated_at) VALUES(?,?,?,?)").bind(orgId,name,now(),now()).run();return orgId;}
async createConversation(orgId:string,title:string){const conversationId=id("conv");await this.env.DB.prepare("INSERT INTO conversations(id,organization_id,title,created_at,updated_at) VALUES(?,?,?,?,?)").bind(conversationId,orgId,title,now(),now()).run();return conversationId;}
async addMessage(orgId:string,conversationId:string,role:string,content:string){const messageId=id("msg");await this.env.DB.prepare("INSERT INTO messages(id,organization_id,conversation_id,role,content,created_at) VALUES(?,?,?,?,?,?)").bind(messageId,orgId,conversationId,role,content,now()).run();return messageId;}
async recentMessages(orgId:string,conversationId:string,limit=30){return this.env.DB.prepare("SELECT id,role,content,created_at FROM messages WHERE organization_id=? AND conversation_id=? ORDER BY created_at DESC LIMIT ?").bind(orgId,conversationId,limit).all();}
async createTask(orgId:string,input:string){const taskId=id("task");const t=now();await this.env.DB.prepare("INSERT INTO tasks(id,organization_id,status,input,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(taskId,orgId,"queued",input,t,t).run();return taskId;}
async getTask(orgId:string,taskId:string){return (await this.env.DB.prepare("SELECT id,status,input,plan_json,result_json,error,created_at,updated_at,completed_at FROM tasks WHERE organization_id=? AND id=?").bind(orgId,taskId).first()) as Record<string,unknown>|null;}
async finishTask(orgId:string,taskId:string,result:unknown,verified:boolean){await this.env.DB.prepare("UPDATE tasks SET status=?,result_json=?,error=NULL,updated_at=?,completed_at=? WHERE organization_id=? AND id=?").bind(verified?"completed":"completed",JSON.stringify(result),now(),now(),orgId,taskId).run();}
async failTask(orgId:string,taskId:string,error:string){await this.env.DB.prepare("UPDATE tasks SET status='failed',error=?,updated_at=? WHERE organization_id=? AND id=?").bind(error,now(),orgId,taskId).run();}
async setTaskStatus(taskId:string,status:string,error?:string){await this.env.DB.prepare("UPDATE tasks SET status=?,error=?,updated_at=? WHERE id=?").bind(status,error??null,now(),taskId).run();}
async createMemory(orgId:string,userId:string|undefined,type:string,content:string,importance:number,expiresAt?:string){const memoryId=id("mem");await this.env.DB.prepare("INSERT INTO memories(id,organization_id,user_id,memory_type,content,importance,expires_at) VALUES(?,?,?,?,?,?,?)").bind(memoryId,orgId,userId??null,type,content,Math.max(0,Math.min(1,importance)),expiresAt??null).run();return memoryId;}
async listMemories(orgId:string,userId?:string){return this.env.DB.prepare("SELECT id,memory_type,content,importance,source,expires_at,created_at,updated_at FROM memories WHERE organization_id=? AND deleted_at IS NULL AND (expires_at IS NULL OR expires_at>datetime('now')) AND (user_id IS NULL OR user_id=?) ORDER BY importance DESC,updated_at DESC LIMIT 100").bind(orgId,userId??null).all();}
async deleteMemory(orgId:string,id:string){await this.env.DB.prepare("UPDATE memories SET deleted_at=?,updated_at=? WHERE organization_id=? AND id=?").bind(now(),now(),orgId,id).run();}
async addAudit(orgId:string,action:string,resourceType:string,resourceId:string,metadata:unknown){await this.env.DB.prepare("INSERT INTO audit_logs(id,organization_id,action,resource_type,resource_id,metadata_json) VALUES(?,?,?,?,?,?)").bind(id("audit"),orgId,action,resourceType,resourceId,JSON.stringify(metadata)).run();}
async addUsage(orgId:string,provider:string,model:string,inputTokens:number,outputTokens:number,latencyMs:number){await this.env.DB.prepare("INSERT INTO usage_events(id,organization_id,provider,model,input_tokens,output_tokens,latency_ms) VALUES(?,?,?,?,?,?,?)").bind(id("usage"),orgId,provider,model,inputTokens,outputTokens,latencyMs).run();}
}
